'use client'
import { useState } from 'react'
import { Loader2 } from 'lucide-react'
import Link from 'next/link'
import { finverseLink } from '@/lib/utils'

export default function PlannerPage() {
  const [form, setForm] = useState({ from: '', to: '', mode: 'Train', days: 3, pilgrims: 2, deity: '', notes: '' })
  const [result, setResult] = useState('')
  const [loading, setLoading] = useState(false)
  const [provider, setProvider] = useState('')
  const [error, setError] = useState('')

  const set = (k: string, v: any) => setForm(f => ({ ...f, [k]: v }))

  const generate = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!form.from || !form.to) return
    setLoading(true); setResult(''); setError('')
    try {
      const res = await fetch('/api/ai/planner', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form),
      })
      const data = await res.json()
      if (data.error) { setError(data.error); return }
      setResult(data.itinerary)
      setProvider(data.provider)
    } catch { setError('Something went wrong. Please try again.') }
    finally { setLoading(false) }
  }

  return (
    <div className="max-w-4xl mx-auto px-6 py-10">
      {/* Header */}
      <div className="mb-8">
        <div className="section-title">Powered by Claude AI</div>
        <h1 className="font-serif text-4xl font-medium">AI Yatra Planner</h1>
        <p className="mt-2 text-sm" style={{ color: 'var(--muted)' }}>
          Get a complete day-wise pilgrimage itinerary with routes, stays, darshan timings and insider tips.
        </p>
      </div>

      {/* Form */}
      <div className="card card-p mb-6">
        <form onSubmit={generate}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="label">Starting City</label>
              <input className="input" placeholder="e.g. Mumbai, Delhi, Pune…" value={form.from} onChange={e => set('from', e.target.value)} required />
            </div>
            <div>
              <label className="label">Destination / Yatra</label>
              <input className="input" placeholder="e.g. Char Dham, Varanasi, Tirupati…" value={form.to} onChange={e => set('to', e.target.value)} required />
            </div>
            <div>
              <label className="label">Travel Mode</label>
              <select className="input" value={form.mode} onChange={e => set('mode', e.target.value)}>
                {['Train', 'Flight', 'Road / Car', 'Bus', 'Mixed'].map(m => <option key={m}>{m}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Duration (Days)</label>
              <input className="input" type="number" min={1} max={30} value={form.days} onChange={e => set('days', parseInt(e.target.value))} />
            </div>
            <div>
              <label className="label">Number of Pilgrims</label>
              <input className="input" type="number" min={1} max={20} value={form.pilgrims} onChange={e => set('pilgrims', parseInt(e.target.value))} />
            </div>
            <div>
              <label className="label">Deity Focus (optional)</label>
              <input className="input" placeholder="e.g. Shiva, Vishnu, Devi…" value={form.deity} onChange={e => set('deity', e.target.value)} />
            </div>
            <div className="md:col-span-2">
              <label className="label">Special Requests (optional)</label>
              <textarea className="input h-20 resize-none" placeholder="Budget trip, elderly pilgrims, specific festivals, vegetarian only, no trekking…"
                value={form.notes} onChange={e => set('notes', e.target.value)} />
            </div>
          </div>
          <button type="submit" disabled={loading || !form.from || !form.to} className="btn btn-primary mt-5 w-full md:w-auto">
            {loading ? <><Loader2 size={16} className="animate-spin" /> Generating Itinerary…</> : 'Generate Pilgrimage Plan'}
          </button>
        </form>
      </div>

      {/* Error */}
      {error && <div className="card card-p mb-4 text-sm" style={{ background: '#FFF0F0', color: 'var(--live)', borderColor: '#FFCDD2' }}>{error}</div>}

      {/* Result */}
      {result && (
        <div className="card card-p">
          <div className="flex items-center justify-between mb-5">
            <h2 className="font-serif text-2xl font-medium">Your Yatra Plan</h2>
            <div className="flex items-center gap-3">
              <span className="badge-gold text-[10px]">Generated by Claude</span>
              <button onClick={() => {
                navigator.clipboard.writeText(result)
              }} className="btn btn-secondary btn-sm">Copy</button>
            </div>
          </div>

          <div className="ai-prose" dangerouslySetInnerHTML={{ __html: result.replace(/\n/g, '<br/>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />

          {/* Bridge cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-8 pt-6 border-t" style={{ borderColor: 'var(--border)' }}>
            <div className="card card-p" style={{ borderColor: 'var(--border2)' }}>
              <h4 className="font-serif text-lg font-medium mb-1">How much will this cost?</h4>
              <p className="text-xs mb-3" style={{ color: 'var(--muted)' }}>Get a detailed cost breakdown with the Yatra Budget calculator.</p>
              <Link href={`/plan/budget?destination=${encodeURIComponent(form.to)}&pilgrims=${form.pilgrims}`} className="btn btn-secondary btn-sm w-full justify-center">
                Calculate Budget →
              </Link>
            </div>
            <div className="card card-p" style={{ borderColor: 'var(--border2)' }}>
              <h4 className="font-serif text-lg font-medium mb-1">Start saving for this yatra</h4>
              <p className="text-xs mb-3" style={{ color: 'var(--muted)' }}>Set a monthly savings goal and track progress until you're ready to go.</p>
              <Link href={`/yatra/goals?yatra=${encodeURIComponent(form.to)}`} className="btn btn-gold btn-sm w-full justify-center">
                Set Savings Goal →
              </Link>
            </div>
          </div>

          {/* FinVerse CTA */}
          <div className="mt-4 rounded-xl p-4 flex items-center justify-between gap-4" style={{ background: 'var(--ivory2)', border: '1px solid var(--border)' }}>
            <div>
              <div className="text-xs font-semibold" style={{ color: 'var(--gold-dk)' }}>Powered by FinVerse</div>
              <p className="text-sm font-medium" style={{ color: 'var(--ink)' }}>Open a dedicated Yatra Fund and start saving today</p>
            </div>
            <a href={finverseLink({ action: 'savings', goal_name: form.to, utm_content: 'planner' })}
              target="_blank" rel="noopener" className="btn btn-gold btn-sm whitespace-nowrap">
              Open Yatra Fund →
            </a>
          </div>
        </div>
      )}
    </div>
  )
}
