'use client'
export const dynamic = 'force-dynamic'
import { useState } from 'react'
import { Loader2, CheckSquare, Square } from 'lucide-react'

interface ChecklistItem {
  name: string
  priority: 'must' | 'recommended'
  note?: string
  checked?: boolean
}
interface ChecklistCategory {
  name: string
  items: ChecklistItem[]
}

export default function ChecklistPage() {
  const [form, setForm] = useState({
    destination: '',
    days: 3,
    mode: 'Train',
    season: 'Winter (Oct–Mar)',
    pilgrim_type: 'Couple',
    special_needs: '',
  })
  const [categories, setCategories] = useState<ChecklistCategory[]>([])
  const [tips, setTips] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [provider, setProvider] = useState('')
  const [checked, setChecked] = useState<Record<string, boolean>>({})

  const set = (k: string, v: any) => setForm(f => ({ ...f, [k]: v }))

  const generate = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!form.destination) return
    setLoading(true)
    try {
      const res = await fetch('/api/ai/checklist', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          destination: form.destination,
          days: form.days,
          mode: form.mode,
          season: form.season,
          pilgrim_type: form.pilgrim_type,
          special_needs: form.special_needs,
        }),
      })
      const data = await res.json()
      if (data.checklist) {
        setCategories(data.checklist.categories || [])
        setTips(data.checklist.destination_tips || [])
        setProvider(data.provider)
        setChecked({})
      }
    } finally {
      setLoading(false)
    }
  }

  const toggleItem = (catIdx: number, itemIdx: number) => {
    const key = `${catIdx}-${itemIdx}`
    setChecked(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const totalItems = categories.reduce((s, c) => s + c.items.length, 0)
  const checkedCount = Object.values(checked).filter(Boolean).length
  const progress = totalItems > 0 ? Math.round((checkedCount / totalItems) * 100) : 0

  return (
    <div className="max-w-4xl mx-auto px-6 py-10">
      <div className="section-title">Powered by Google Gemini</div>
      <h1 className="font-serif text-4xl font-medium mb-2">Packing Checklist</h1>
      <p className="text-sm mb-8" style={{ color: 'var(--muted)' }}>
        Destination-specific checklist generated by AI. Never forget your dhoti, altitude gear, or temple essentials.
      </p>

      {/* Form */}
      <div className="card card-p mb-8">
        <form onSubmit={generate}>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="md:col-span-2">
              <label className="label">Destination</label>
              <input className="input" placeholder="e.g. Kedarnath, Tirupati, Amarnath, Char Dham…"
                value={form.destination} onChange={e => set('destination', e.target.value)} required />
            </div>
            <div>
              <label className="label">Duration (Days)</label>
              <input className="input" type="number" min={1} max={30} value={form.days}
                onChange={e => set('days', parseInt(e.target.value))} />
            </div>
            <div>
              <label className="label">Travel Mode</label>
              <select className="input" value={form.mode} onChange={e => set('mode', e.target.value)}>
                {['Train','Flight','Car/Bus','Trek only','Mixed'].map(m => <option key={m}>{m}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Season</label>
              <select className="input" value={form.season} onChange={e => set('season', e.target.value)}>
                {['Winter (Oct–Mar)','Summer (Apr–Jun)','Monsoon (Jul–Sep)'].map(s => <option key={s}>{s}</option>)}
              </select>
            </div>
            <div>
              <label className="label">Pilgrim Type</label>
              <select className="input" value={form.pilgrim_type} onChange={e => set('pilgrim_type', e.target.value)}>
                {['Solo','Couple','Family with kids','Group','Senior pilgrim','First-time pilgrim'].map(p => <option key={p}>{p}</option>)}
              </select>
            </div>
            <div className="md:col-span-2">
              <label className="label">Special Needs (optional)</label>
              <input className="input" placeholder="e.g. elderly parent, medical conditions, no trekking…"
                value={form.special_needs} onChange={e => set('special_needs', e.target.value)} />
            </div>
          </div>
          <button type="submit" disabled={loading || !form.destination} className="btn btn-primary mt-5">
            {loading ? <><Loader2 size={15} className="animate-spin" /> Generating checklist…</> : 'Generate Packing List'}
          </button>
        </form>
      </div>

      {/* Results */}
      {categories.length > 0 && (
        <div>
          {/* Progress */}
          <div className="card card-p mb-6">
            <div className="flex items-center justify-between mb-2">
              <div>
                <span className="font-serif text-xl font-medium">{form.destination} Checklist</span>
                <span className="ml-3 badge-gold text-[10px]">Gemini AI</span>
              </div>
              <span className="text-sm font-medium" style={{ color: checkedCount === totalItems ? '#2E7D32' : 'var(--muted)' }}>
                {checkedCount}/{totalItems} packed
              </span>
            </div>
            <div className="h-2 rounded-full overflow-hidden" style={{ background: 'var(--ivory3)' }}>
              <div className="h-full rounded-full transition-all duration-500"
                style={{ width: `${progress}%`, background: progress === 100 ? '#2E7D32' : 'var(--crimson)' }} />
            </div>
            {progress === 100 && (
              <p className="text-sm mt-2 font-medium" style={{ color: '#2E7D32' }}>🎉 You're all packed! Have a blessed yatra.</p>
            )}
          </div>

          {/* Destination tips */}
          {tips.length > 0 && (
            <div className="card card-p mb-6" style={{ background: 'var(--ivory2)' }}>
              <div className="section-title mb-2">💡 Destination Tips</div>
              <ul className="space-y-1.5">
                {tips.map((tip, i) => (
                  <li key={i} className="text-sm flex items-start gap-2" style={{ color: 'var(--muted)' }}>
                    <span className="text-gold-500 flex-shrink-0 mt-0.5">→</span> {tip}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Checklist categories */}
          <div className="space-y-4">
            {categories.map((cat, ci) => (
              <div key={ci} className="card card-p">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="font-serif text-lg font-medium">{cat.name}</h3>
                  <span className="text-xs" style={{ color: 'var(--muted2)' }}>
                    {cat.items.filter((_, ii) => checked[`${ci}-${ii}`]).length}/{cat.items.length}
                  </span>
                </div>
                <div className="space-y-2">
                  {cat.items.map((item, ii) => {
                    const key = `${ci}-${ii}`
                    const done = !!checked[key]
                    return (
                      <label key={ii} className="flex items-start gap-3 cursor-pointer group">
                        <button type="button" onClick={() => toggleItem(ci, ii)}
                          className="flex-shrink-0 mt-0.5 transition-colors"
                          style={{ color: done ? 'var(--crimson)' : 'var(--muted2)' }}>
                          {done ? <CheckSquare size={17} /> : <Square size={17} />}
                        </button>
                        <div className={done ? 'opacity-50' : ''}>
                          <div className="flex items-center gap-2">
                            <span className="text-sm" style={{ color: 'var(--ink)', textDecoration: done ? 'line-through' : 'none' }}>
                              {item.name}
                            </span>
                            <span className={`text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded ${
                              item.priority === 'must'
                                ? 'bg-red-50 text-red-600'
                                : 'bg-amber-50 text-amber-700'
                            }`}>
                              {item.priority === 'must' ? 'Must' : 'Rec'}
                            </span>
                          </div>
                          {item.note && (
                            <p className="text-xs mt-0.5" style={{ color: 'var(--muted2)' }}>{item.note}</p>
                          )}
                        </div>
                      </label>
                    )
                  })}
                </div>
              </div>
            ))}
          </div>

          {/* Actions */}
          <div className="flex gap-3 mt-6">
            <button
              onClick={() => {
                const text = categories.map(c =>
                  `${c.name}\n${c.items.map(i => `  ${i.priority === 'must' ? '✓' : '○'} ${i.name}${i.note ? ` (${i.note})` : ''}`).join('\n')}`
                ).join('\n\n')
                navigator.clipboard.writeText(`${form.destination} Packing List\n\n${text}`)
              }}
              className="btn btn-secondary btn-sm">
              Copy List
            </button>
            <button
              onClick={() => {
                const msg = `*${form.destination} Packing Checklist*\n_from DivyaDarshan_\n\n` +
                  categories.map(c => `*${c.name}*\n${c.items.filter(i => i.priority === 'must').map(i => `☐ ${i.name}`).join('\n')}`).join('\n\n')
                window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`, '_blank')
              }}
              className="btn btn-secondary btn-sm">
              Share on WhatsApp
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
